# Start with Rubocop's default style
# (Hound CI does not support inherit_from URLs)
# inherit_from: https://github.com/bbatsov/rubocop/blob/v0.39.0/config/default.yml
inherit_from: ./config/rubocop/default.yml
# Europeana specific changes go below
Metrics/LineLength:
  Description: Limit lines to 140 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 140
  AllowURI: true
  URISchemes:
  - http
  - https
