notifications:
  email: false
sudo: false
language: ruby
rvm:
  - 2.5.0
bundler_args: --without development:production:doc:localeapp:profiling
cache:
  bundler: true
addons:
  postgresql: "9.4"
  firefox: latest
before_script:
  - "psql -c 'create database europeana_channels_blacklight_test;' -U postgres"
  - "cp -r ./deploy/travis/. ."
  - "bundle exec rake db:test:prepare"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
env:
  - RAILS_ENV=test
services:
  - redis-server
