---
# Free re-use / REUSABILITY="open"
open:
  public:
    pattern: "https?://creativecommons.org/publicdomain/mark"
    url: "https://creativecommons.org/publicdomain/mark/1.0/"
    template_license: public
  cc0:
    pattern: "https?://creativecommons.org/(licenses/)?publicdomain/zero"
    url: "https://creativecommons.org/publicdomain/zero/1.0/"
  cc_by:
    pattern: "https?://creativecommons.org/licenses/by/"
    url: "https://creativecommons.org/licenses/by/4.0"
  cc_by_sa:
    pattern: "https?://creativecommons.org/licenses/by-sa"
    url: "https://creativecommons.org/licenses/by-sa/4.0"
# Limited re-use / REUSABILITY="restricted"
restricted:
  cc_by_nc:
    pattern: "https?://creativecommons.org/licenses/by-nc/"
    url: "https://creativecommons.org/licenses/by-nc/4.0"
  cc_by_nc_nd:
    pattern: "https?://creativecommons.org/licenses/by-nc-nd"
    url: "https://creativecommons.org/licenses/by-nc-nd/4.0"
  cc_by_nc_sa:
    pattern: "https?://creativecommons.org/licenses/by-nc-sa"
    url: "https://creativecommons.org/licenses/by-nc-sa/4.0"
  cc_by_nd:
    pattern: "https?://creativecommons.org/licenses/by-nd"
    url: "http://creativecommons.org/licenses/by-nd/4.0/"
  out_of_copyright_non_commercial:
    pattern: "https?://www.europeana.eu/rights/out-of-copyright-non-commercial"
    template_license: OOC
  rs_inc_edu:
    pattern: "https?://rightsstatements.org/vocab/InC-EDU/*"
    url: "http://rightsstatements.org/vocab/InC-EDU/1.0/"
  rs_noc_nc:
    pattern: "https?://rightsstatements.org/vocab/NoC-NC/*"
    url: "http://rightsstatements.org/vocab/NoC-NC/1.0/"
  rs_noc_oklr:
    pattern: "https?://rightsstatements.org/(vocab|page)/NoC-OKLR/*"
    url: "http://rightsstatements.org/vocab/NoC-OKLR/1.0/"
# No re-use / REUSABILITY="permission"
permission:
  rrfa:
    pattern: "https?://www.europeana.eu/rights/rr-f"
    template_license: RR_free
  rrpa:
    pattern: "https?://www.europeana.eu/rights/rr-p"
    template_license: RR_paid
  rrra:
    pattern: "https?://www.europeana.eu/rights/rr-r/"
    template_license: RR_restricted
  ucs:
    pattern: "https?://www.europeana.eu/rights/unknown"
    template_license: unknown
  orphan_work:
    pattern: "https?://www.europeana.eu/rights/test-orphan"
    template_license: orphan
  rs_inc:
    pattern: "https?://rightsstatements.org/vocab/InC/*"
    url: "http://rightsstatements.org/vocab/InC/1.0/"
  rs_inc_ow_eu:
    pattern: "https?://rightsstatements.org/vocab/InC-OW-EU/*"
    url: "http://rightsstatements.org/vocab/InC-OW-EU/1.0/"
  rs_cne:
    pattern: "https?://rightsstatements.org/vocab/CNE/*"
    url: "http://rightsstatements.org/vocab/CNE/1.0/"
