---
# Free re-use / REUSABILITY="open"
open:
  cc0:
    pattern: "http://creativecommons.org/(licenses/)?publicdomain/zero"
    api_query: "http://creativecommons.org/*publicdomain/zero*"
  cc_by:
    pattern: "http://creativecommons.org/licenses/by/"
  cc_by_sa:
    pattern: "http://creativecommons.org/licenses/by-sa"
  pdm:
    pattern: "http://creativecommons.org/publicdomain/mark"
    template_license: public
# Limited re-use / REUSABILITY="restricted"
restricted:
  cc_by_nc:
    pattern: "http://creativecommons.org/licenses/by-nc/"
  cc_by_nc_nd:
    pattern: "http://creativecommons.org/licenses/by-nc-nd"
  cc_by_nc_sa:
    pattern: "http://creativecommons.org/licenses/by-nc-sa"
  cc_by_nd:
    pattern: "http://creativecommons.org/licenses/by-nd"
  out_of_copyright_non_commercial:
    pattern: "http://www.europeana.eu/rights/out-of-copyright-non-commercial"
    template_license: OOC
# No re-use / REUSABILITY="permission"
permission:
  rrfa:
    pattern: "http://www.europeana.eu/rights/rr-f"
    template_license: RR_free
  rrpa:
    pattern: "http://www.europeana.eu/rights/rr-p"
    template_license: RR_paid
  rrra:
    pattern: "http://www.europeana.eu/rights/rr-r/"
    template_license: RR_restricted
  ucs:
    pattern: "http://www.europeana.eu/rights/unknown"
    template_license: unknown
  orphan_work:
    pattern: "http://www.europeana.eu/rights/test-orphan"
    template_license: orphan
