---
:query: '(what: archaeology) OR (what: archäologie) OR (what: Altertümerkunde)
  OR (what: fornminne) OR (what: arqueologia) OR (what: archéologie) OR (what:
  arkeologi) OR (what: artefact) OR (what: artifact) OR (what: prehistory) OR
  (what: préhistoire) OR (what: urgeschichte) OR Palaeolit OR Paleoli OR
  neolitik OR neolithic OR mesolit OR "iron age" OR "bronze age" OR "stone age"
  OR (what: "rock art") OR (what: hällristning) OR (PROVIDER: CARARE) OR
  (PROVIDER: "3D ICONS") OR (DATA_PROVIDER: "The British Museum and The
  Portable Antiquities Scheme") OR (DATA_PROVIDER: "Rijksmuseum van Oudheden")
  NOT (DATA_PROVIDER: "Nederlands Architectuurinstituut" OR DATA_PROVIDER: "The
  National Architectural Heritage Board" OR DATA_PROVIDER: "Europeana
  1914-1918")'
