---
:query: '(what: "fine art") OR (what: "beaux arts") OR (what: "bellas artes")
  OR (what: "belle arti") OR (what: "schone kunsten") OR (what:"konst") OR
  (what: paintings) OR (what: schilderij) OR (what: pintura) OR (what:
  peinture) OR (what: dipinto) OR (what: malerei) OR (what: sculpture) OR
  (what: drawing) OR (what: poster) OR (what: tapestry) OR (what: jewellery)
  OR (what: miniature) OR (what: prints) OR what: träsnitt OR what: holzschnitt
  OR what: woodcut OR what: lithography OR what: chiaroscuro OR what: "old
  master print" OR (what: Mannerism) OR (what: Rococo) OR (what: Impressionism)
  OR (what: Expressionism) OR (what: Romanticism) OR (what: "Neo-Classicism")
  OR (what: "Pre-Raphaelite") OR (what: Symbolism) OR (what: Surrealism) OR
  (what: Cubism) OR (what: "Art Deco") OR (what: Dadaism) OR (what: "De Stijl")
  OR (what: "Pop Art") OR (what: "art nouveau") OR (what: "art history") OR
  (what: "http://vocab.getty.edu/aat/300041273") OR (what: "histoire de
  l''art") OR (what: kunstgeschichte) OR (what: "estudio de la historia del
  arte") OR (what: Kunstgeschiedenis) NOT (what: "printed serial" OR
  what:"printedbook" OR "printing paper" OR "printed music" OR
  DATA_PROVIDER:"NALIS Foundation" OR PROVIDER:"OpenUp!" OR PROVIDER:"EFG -
  The European Film Gateway" OR DATA_PROVIDER: "Malta Aviation Museum
  Foundation")'
