---
:hero: '//www.rijksmuseum.nl/assetimage2.jsp?id=SK-A-2725'
:promoted:
- :is_channel: true
  :title: Music
  :url: /portal/channels/music
  :wide: true
  :bg_image: sample/thumb-music.jpg
- :is_exhibition: true
  :title: Recording and Playing Machines
  :bg_image: sample/thumb-machines.jpg
  :url: 'http://europeana.exhibitions.eu/exhibits/show/recording-and-playing-machines'
- :is_exhibition: true
  :title: Photography on a Silver Plate
  :bg_image: sample/thumb-photography.jpg
  :url: 'https://www.google.com/culturalinstitute/exhibit/photography-on-a-silver-plate/gQxWH0VE?hl'
- :is_exhibition: true
  :title: European Film and the First World War
  :bg_image: sample/thumb-expo-film.jpg
  :url: 'http://exhibition.europeanfilmgateway.eu/efg1914/welcome'
- :title: Europeana 1914-1918
  :url: 'http://www.europeana1914-1918.eu'
  :bg_image: sample/thumb-1418.jpg
- :is_new: true
  :title: Europeana monuments now in Google Field Trip
  :url: 'http://pro.europeana.eu/blogpost/reach-cultural-tourists-through-europeana-in-googles-field-trip'
