---
content:
  promoted:
  - is_channel: true
    title: Music
    url: /portal/channels/music
    wide: true
    bg_image: sample/thumb-music.jpg
  - is_exhibition: true
    title: Recording and Playing Machines
    bg_image: sample/thumb-machines.jpg
    url: 'http://europeana.exhibitions.eu/exhibits/show/recording-and-playing-machines'
  - is_exhibition: true
    title: Photography on a Silver Plate
    bg_image: sample/thumb-photography.jpg
    url: 'https://www.google.com/culturalinstitute/exhibit/photography-on-a-silver-plate/gQxWH0VE?hl'
  - is_exhibition: true
    title: European Film and the First World War
    bg_image: sample/thumb-expo-film.jpg
    url: 'http://exhibition.europeanfilmgateway.eu/efg1914/welcome'
  - title: Europeana 1914-1918
    url: 'http://www.europeana1914-1918.eu'
    bg_image: sample/thumb-1418.jpg
    is_featured_site: true
  - is_new: true
    title: Europeana monuments now in Google Field Trip
    url: 'http://pro.europeana.eu/blogpost/reach-cultural-tourists-through-europeana-in-googles-field-trip'
  hero_config:
    hero_image: sample/search_hero_1.jpg
    brand_position: brand-bottomleft
    brand_opacity: brand-opacity75
    attribution_title: Insects and Fruit
    attribution_creator: Jan van Kessel
    attribution_institution: Rijksmuseum
    attribution_url: /portal/record/90402/SK_A_793.html
    license_CC-ND-NC-SA: false
    license_public: true
