---
:hero: music.jpg
:query: ! 'PROVIDER: "DISMARC+-+EuropeanaConnect" OR PROVIDER:
  "Cité+de+la+musique" OR PROVIDER:
  "IRCAM-Institut+de+Recherche+et+Coordination+Acoustique%2FMusique" OR
  (what: Music) OR (what: Sheet Music) OR (what: Musical Instrument) OR
  (what: sound) OR (what: partitur) OR (what: oper) NOT DATA_PROVIDER:
  "Progetto ArtPast- CulturaItalia"'
